### PR TITLE
[Draft] Using KapChat

### PR DESCRIPTION
**Pull request by Aaron128l**
A draft of using KapChat. Will provide images if really needed but I personally don't believe it does. Feel free to edit all of my "weird" grammar or spelling. Thus the draft.

### CODE REVIEW

**Comment by TruthfulUK** [comment]
Thanks, will check this out some more tomorrow when I have some spare time :)

**Comment by Aaron128l** [comment]
Sounds like a plan. Thank you :D

**Comment by TruthfulUK** [comment]
Merged, looks like it'll need some markdown fiddling before going out of draft

You can see it at https://www.twitchtips.com/using-kapchat/

**Comment by Aaron128l** [comment]
Ok I'll start fiddling as well as re-adjusting the overall organization.as a whole.

**Pull request merged**
